# vim:set ft=sh
# MODULES
# The mkinitcpio command can be used to add binary-only modules to the
# initramfs, for example for filesystems not handled by udev.
MODULES=()

# BINARIES
# This setting allows you to add additional binaries to the initramfs
# This setting is especially useful for creating custom installers.
BINARIES=()

# FILES
# This setting allows you to add additional files to the initramfs
FILES=()

# HOOKS
# This setting allows you to add additional custom hooks to the mkinitcpio
# initramfs
HOOKS=(base udev archiso block filesystems keyboard)

# COMPRESSION
# Use this to compress the initramfs image. Use 'cat' to create an
# uncompressed image.
COMPRESSION=(zstd)
