#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

[options]
Architecture = x86_64
RootDir     = /
DBPath      = /var/lib/pacman/
CacheDir    = /var/cache/pacman/pkg/
LogFile     = /var/log/pacman.log
GPGDir      = /etc/pacman.d/gnupg/
HoldPkg     = pacman glibc man-db bash syslog-ng
#IgnorePkg   =
#IgnoreGroup =
#NoUpgrade   =
#NoExtract   =
# Misc options
#UseSyslog
#Color
#TotalDownload
CheckSpace
#VerbosePkgLists

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its manpage), as well as unsigned packages.

# Arch Linux repositories
[core]
SigLevel = Never
Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = Never
Include = /etc/pacman.d/mirrorlist

[chaotic-aur]
SigLevel = Never
Server = https://r2.garudalinux.org/repos/chaotic-aur/x86_64
